---
- hosts: 172.31.42.162
  become: True
  tasks:
    - name: Install Apache server
      yum:
        name: httpd
        state: present
    - name: Start apache server
      service:
        name: httpd
        state: started
    - name: Enable Apache on reboot
      service:
        name: httpd
        enabled: True
